[[Package]]
path="/monster-id"
repo="https://github.com/techknowlogick/go-monsterID.git"
packages=[]
url="https://github.com/techknowlogick/go-monsterID"
name="go-monsterID"

[[Package]]
path="/wavatars"
repo="https://github.com/techknowlogick/go-wavatars.git"
packages=[]
url="https://github.com/techknowlogick/go-wavatars"
name="go-wavatars"

[[Package]]
path="/retricon"
repo="https://github.com/techknowlogick/go-retricon.git"
packages=[]
url="https://github.com/techknowlogick/go-retricon"
name="go-retricon"

[[Package]]
path="/mysteryperson-id"
repo="https://github.com/techknowlogick/go-mysteryperson-id.git"
packages=[]
url="https://github.com/techknowlogick/go-mysteryperson-id"
name="go-mysteryperson-id"

[[Package]]
path="/nobody-id"
repo="https://github.com/techknowlogick/go-nobody-id.git"
packages=[]
url="https://github.com/techknowlogick/go-nobody-id"
name="go-nobody-id"

[[Package]]
path="/oauth2-xorm"
repo="https://github.com/techknowlogick/go-oauth2-xorm.git"
packages=[]
url="https://github.com/techknowlogick/go-oauth2-xorm"
name="go-oauth2-xorm"

[[Package]]
path="/oauth2-gorm"
repo="https://github.com/techknowlogick/go-oauth2-gorm.git"
packages=[]
url="https://github.com/techknowlogick/go-oauth2-gorm"
name="go-oauth2-gorm"

[[Package]]
path="/identicon"
repo="https://github.com/techknowlogick/go-identicon.git"
packages=[]
url="https://github.com/techknowlogick/go-identicon"
name="go-identicon"

[[Package]]
path="/paypal-fee-computer"
repo="https://github.com/techknowlogick/go-paypal-fee-computer.git"
packages=[]
url="https://github.com/techknowlogick/go-paypal-fee-computer"
name="go-paypal-fee-computer"

[[Package]]
path="/shiori"
repo="https://github.com/techknowlogick/shiori.git"
packages=["cmd","cmd/account","cmd/serve","database","model"]
url="https://github.com/techknowlogick/shiori"
name="shiori"
